project_name: gojsontoenv
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -v
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
- image_templates:
    - "prune/{{.ProjectName}}:latest-amd64"
    - "prune/{{.ProjectName}}:{{ .Tag }}-amd64"
    - "prune/{{.ProjectName}}:v{{ .Major }}-amd64"
    - "prune/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}-amd64"
  dockerfile: Dockerfile
  extra_files:
    - main.go
    - go.mod
    - go.sum
  use_buildx: true
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/prune998/gojsontoenv
  - --label=org.opencontainers.image.source=https://github.com/prune998/gojsontoenv
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
  - --build-arg=VERSION={{ .Version }}
  - --build-arg=COMMIT={{ .Commit }}
  - --build-arg=DATE={{ .Date }}
docker_manifests:
- name_template: "prune/{{.ProjectName}}:{{ .Tag }}"
  image_templates:
  - "prune/{{.ProjectName}}:{{ .Tag }}-amd64"
